# SITE SETTINGS
title: "MDrights"
tagline: "A Geek of Digital Freedom and Privacy"
description: ""

url: "https://mdrights.github.io"
baseurl: "https://mdrights.github.io"
timezone: UTC
excerpt_separator: <!--more-->
email: 

# Build settings
markdown: kramdown
#redcarpet: 
#  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data", "fenced_code_blocks"]
exclude: [Gemfile, Gemfile.lock, README.md]
enforce_ssl: mdrights.github.io
permalink: /posts/:year/:month/:title.html

# Plugins
gems:
  - jemoji
emoji:
  src: "/images"

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      excerptable: true
      sitemap: true
      comments: true
      layout: post
  -
    scope:
      path: ""
    values:
      cc_by_sa: true
  -
    scope:
      path: "tags"
    values:
      layout: tag
